# Generated by Django 4.2.4 on 2023-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Company', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Salary', models.CharField(max_length=255)),
                ('Description', models.TextField()),
            ],
        ),
    ]
